<?php if (!empty($this->rep_photo)) {
    $reps = $this->rep_photo;
    ?>
<div class="row justify-content-center">
    <?php for ($i=1; $i<6; $i++) { ?>
    <div id="dossier<?php echo $i; ?>" class="col-12 col-md-6 col-lg-4 text-center">
        <a href="<?php echo $this->url(array('controller' => 'galerie', 'action' => 'dossier', 'folder' => $reps[$i-1]), null, true); ?>">
            <img src='<?php echo ROOT_TO_PUBLIC; ?>/image/icon-photo.png'  alt="" /><?php echo $reps[$i-1]; ?>
        </a>
    </div>
    <?php } ?>
<?php }?>
</div>

<?php /* sous dossier s'ils existent */ if (isset($this->sousdossier) && !empty($this->sousdossier)) { ?>
Eléments du dossier <?php echo $this->sousDossier; ?> :
<div id="sousdossier" >
<ul>
    <?php foreach ($this->sousdossier as $dossier) { ?> 
	<li>
        <a href="<?php echo $this->url(array('controller' => 'galerie', 'action' => 'dossier', 'subfolder' => $dossier)); ?>"
        title="<?php echo $dossier; ?>"><?php echo $dossier; ?>
        </a>
	</li>
    <?php } ?>
</ul>
</div>
<?php }?>

<?php /* Les photos du sous dossier ! */ if (isset($this->photos) && !empty($this->photos)) { ?>
<div class="row justify-content-start">
	<?php foreach ($this->photos as $photo) { ?>
	<a href="<?php echo $this->smallToBig($photo['content']); ?>" class="col-12 col-sm-6 col-md-4 col-lg-3 col-xl-2 text-center thickbox mb-2">
		<img class="imagecontent" src="<?php echo $photo['content']; ?>" alt="" <?php if (isset($photo['larghaut'])) echo $photo['larghaut']; else echo 'height="100"';?> />
	</a>
    <?php } ?>
</div>
<?php } 