<div class="boxe" id="ajouter">
	<p>Pour ajouter un nouveau message sur le livre d'or, cliquer <a href="<?php echo $this->url(array('action' => 'newmessage')); ?>">ici</a></p>
</div>
<div id="livrecontainer">
    <div id="left" class="bandes"></div>
    <div id="right" class="bandes"></div>
    <div id="middle">
        <?php foreach ($this->messages as $message) { ?>
        <div class="messagebox">
            <div class="authordate">Posté par <span class="important"><?php echo $message['Auteur']; ?></span>, 
                le <span class="important"><?php echo $message['Date']; ?></span>
                à <span class="important"><?php echo $message['Heure']; ?></span>
                <span class="suppr">
            		<a href="<?php echo $this->url(array('controller' => 'livreor', 'action' => 'suppression', 'id' => $message['Keyfield']));?>">
            			<img src="/public/image/delete.png" height="12px" title="Supprimer le message" alt="supprimer"/>
            		</a>
            	</span>
            </div>
            <div class="message"><?php echo $message['Commentaire']; ?>
        </div>        
        </div>
        <?php } ?>
    </div>
</div>