<h3>
    <a href="<?php echo $this->url(array('controller' => "agenda", "action" => "index"), "", true); ?>">
        &nbsp;Agenda&nbsp;
    </a>
</h3>

<?php $i = 0; ?>
<?php
foreach ($this->actualites as $actualite) {
    if ($i === 3) // Maximum 3 actualités dans la vue de l'acceuil
        break;
    $i++;
    ?>
    <div class="actualite">
        <span class="bold"><?php echo $actualite['date']; ?></span><br />
        <a href="<?php echo $this->url(array('controller' => "agenda", "action" => "index"), "", true) . '#' . $actualite['id']; ?>">
    <?php echo $actualite['titre']; ?>
        </a>
    </div>
<?php } ?>