<div id="contentdossier">
    <p>Pour vous inscrire nous vous donnons rendez-vous au 
        <span class="bold">forum des associations d'Eybens le 7 septembre.</span> 
        N'oubliez pas de vous munir 
        d'une <span class="bold">photo d'identité</span> ainsi que d'un 
        <span class="bold">certificat médical.</span>
    </p>
    <p>
        Vous pouvez également nous 
        <span class="bold">envoyer le dossier d'inscription par courrier</span>
        à l'adresse suivante : 
    </p>
    <div class="center">Association impulsion <br />
        3, avenue du vercors <br />
        38240 Meylan</div>

    <p>Pour ceci, télécharger le dossier d'inscription <a href="<?php echo ROOT_TO_PUBLIC; ?>/document/dossier d'inscription.zip" onclick="window.open(this.href); return false;">ici</a>.</p>
    <p>
        Avant de l'envoyer, 
        <span class="bold">vérifier qu'il comprend les documents suivants :</span>
    </p>
    <ul>
        <li>La fiche de renseignements</li>
        <li>Le tableau des différents cours avec votre choix</li>
        <li>Les deux annexes (1 et 2)</li>
        <li>L'annexe 3 qui comprend l'autorisation parentale (pour les mineurs) ainsi que le droit à l'image (pour tous)</li>
        <li>Une photo d'identité</li>
        <li>Un certificat médical datant de moins d'un an</li>
    </ul>
    <p>Pour tout renseignement, n'hésitez pas à nous <a href="<?php echo $this->url(array('controller' => 'liens', 'action' => 'index')) ?>">contacter</a>.</p>
    <h2>Cours d'essai</h2>
    <p>
        Il est possible de venir faire un cours d'essai. Pour ceci n'hésitez pas 
        à réserver votre place auprès de la professeure. Pour la contacter, 
        cliquer <a href="<?php echo $this->url(array('controller' => 'liens', 'action' => 'index')) ?>">ici</a>.</p>
</div>