<div class="mt-2">
    <p>Pour vous inscrire nous vous donnons rendez-vous à
        <span class="bold">la salle des fêtes à Eybens</span>
        <span class="font-weight-bold">le samedi 9 septembre 2023 de 9h à 13h</span>.
        <br/>
        N'oubliez pas de vous munir 
        d'une <span class="font-weight-bold">photo d'identité</span> ainsi que d'un 
        <span class="font-weight-bold">certificat médical</span> (si l'ancien date de plus de 3 ans).
    </p>
    <p>
        Vous pouvez également nous 
        <span class="bold">envoyer le dossier d'inscription par courrier</span>
        à l'adresse suivante : 
    </p>
    <div class="center">Mme PETROWITCH, Association Impulsion <br />
        29 rue Jean Moulin<br />
        38320 Eybens</div>

    <p class="alert-primary alert mt-2">Pour ceci, télécharger le dossier d'inscription <a href="<?php echo ROOT_TO_PUBLIC; ?>/document/dossier d'inscription.zip" onclick="window.open(this.href); return false;">ici</a>.</p>
    <div class="alert-warning alert">
        Avant de l'envoyer, 
        <span class="font-weight-bold">vérifier qu'il comprend les documents suivants :</span>
        <ul class="mt-2 mb-0">
            <li>La fiche de renseignements</li>
            <li>Le tableau des différents cours avec votre choix</li>
            <li>Les deux annexes (1 et 2)</li>
            <li>L'annexe 3 qui comprend l'autorisation parentale (pour les mineurs) ainsi que le droit à l'image (pour tous)</li>
            <li>Le règlement en un ou trois chèques</li>
            <li>Une photo d'identité</li>
            <li>Un certificat médical datant de moins de 3 ans</li>
        </ul>
    </div>
    <p>Pour tout renseignement, n'hésitez pas à nous <a href="<?php echo $this->url(array('controller' => 'liens', 'action' => 'index')) ?>">contacter</a>.</p>
    <h4>Cours d'essai</h4>
    <p>
        Il est possible de venir faire un cours d'essai. Pour ceci n'hésitez pas 
        à réserver votre place auprès de la professeure.
        Prix: 5€ récupérables sur la cotisation.<br/>
         Pour la contacter, 
        cliquer <a href="<?php echo $this->url(array('controller' => 'liens', 'action' => 'index')) ?>">ici</a>.</p>
</div>