<table>
    <tr>
        <td>
            <a href="<?php echo $this->url(array('controller' => "cours", "action" => "plan"), "", true); ?>">
                Plan<br/>
                <img src='<?php echo ROOT_TO_PUBLIC; ?>/image/plan.png' 
                     alt=""
                     width="256"
                     height="256" />
            </a>
        </td>
        <td>
            <a href="<?php echo $this->url(array('controller' => "cours", "action" => "planning"), "", true); ?>">
                Planning<br/>
                <img src='<?php echo ROOT_TO_PUBLIC; ?>/image/calendrier.png' 
                     alt=""
                     width="256"
                     height="256" />
            </a>
        </td>
        <td>
            <a href="<?php echo $this->url(array('controller' => "cours", "action" => "tarif"), "", true); ?>">
                Tarifs<br/>
                <img src='<?php echo ROOT_TO_PUBLIC; ?>/image/tarif.png' 
                     alt=""
                     width="256"
                     height="256" />
            </a>
        </td>
        <td>
            <a href="<?php echo $this->url(array('controller' => "cours", "action" => "dossier"), "", true); ?>">
                Inscription<br/>
                <img src='<?php echo ROOT_TO_PUBLIC; ?>/image/dossier.png' 
                     alt=""
                     width="256"
                     height="256" />
            </a>
        </td>
    </tr>
</table>

