<div id="planningcontenu">
<table>
	<caption>Horaire des différents groupes 2018 - 2019</caption>
	<tr>
		<th>Âge</th>
		<th>Année de naissance</th>
		<th>Nom du groupe</th>
		<th>Jour</th>
		<th>Horaire</th>
		<th>Lieu</th>
	</tr>
	<?php foreach ($this->groupes as $group) { ?>
	<tr>
		<td><?php echo $group["age"]; ?></td>			
		<td><?php echo $group["age"] !== "Adultes" ? $group["annees_naissance"] : ""; ?></td>			
		<td><?php echo $group["nom"]; ?></td>			
		<td><?php echo $group["jour"]; ?></td>			
		<td><?php echo $group["horaire"]; ?></td>			
		<td><?php echo $group["lieu"]; ?></td>			
	</tr>
	<?php } ?>
</table>
</div>