<div id="entete">Les cours se déroulent soit à l'Odyssée soit à la Maison des Associations d'Eybens.</div>
<div id="plan">
<script type="text/javascript"
        src="http://maps.googleapis.com/maps/api/js?key=AIzaSyDexSbyGj3ud8g9DjdJ_3wRP-SGysa2lwE&amp;sensor=false">
</script>
<script type="text/javascript"
        src="<?php echo ROOT_TO_PUBLIC; ?>/js/map_generation.js">
</script>

L'Odyssée (89,avenue Jean Jaurès 38320 Eybens)
<div id="map1" class="maps"></div>

La maison des associations (8 rue Jean Macé 38320 Eybens)
<div id="map2" class="maps"></div>

</div>