<div class="alert-primary alert mt-2">Les cours se déroulent sur Eybens
<ul class="mb-0">
	<li>Soit à l’Odyssée</li>
	<li>Soit à l’école des Ruires</li>
</ul>
</div>
<div id="plan">
<script type="text/javascript"
        src="http://maps.googleapis.com/maps/api/js?key=AIzaSyDexSbyGj3ud8g9DjdJ_3wRP-SGysa2lwE&amp;sensor=false">
</script>
<script type="text/javascript"
        src="<?php echo ROOT_TO_PUBLIC; ?>/js/map_generation.js">
</script>

<h4>L'Odyssée - 89, avenue Jean Jaurès 38320 Eybens</h4>
<p>
Les cours se déroulent dans la salle de danse située au premier étage du bâtiment.<br/>
Vous pouvez vous garer à l’arrière dans le grand parking prévu à cet effet.<br/>
Entrée à l’avant du bâtiment du côté cours Jean-Jaurès ou à l’arrière coté parking puis suivre les flèches « salle de danse ».
</p>
<div id="map1" class="maps"></div>

<h4>Ecole des Ruires - 1 place René Char 38320 eybens</h4>
<p>
Les cours se déroulent au premier étage de l’école.<br/>
Vous pouvez vous garer sur l’avenue d’Echirolles en face du cimetière, dans la rue Montesquieu le long du centre 
de l’Iliade ou devant les commerces autour de la place Condorcet.<br/>
Entrée au niveau du préau de l’école des Ruires, deuxième porte à gauche à côté de celle de l’école maternelle.<br/>
Pour ne pas déranger le cours d’avant merci d’attendre derrière la porte en haut devant l’ascenseur.
</p>
<div id="map3" class="maps"></div>


</div>