<div id="planningcontenu">
<table>
	<caption>Horaire des différents groupes 2013 - 2014</caption>
	<tr>
		<th>Âge</th>
		<th>Année de naissance</th>
		<th>Nom du groupe</th>
		<th>Jour</th>
		<th>Horaire</th>
		<th>Lieu</th>
	</tr>
	<tr>
		<td>4-5 ans</td>
		<td>2008-2009</td>
		<td>Éveil</td>
		<td>Vendredi</td>
		<td>16h30-17h15</td>
		<td>Odyssée</td>
	</tr>
	<tr>
		<td>4-5 ans</td>
		<td>2008-2009</td>
		<td>Éveil Samedi</td>
		<td>Samedi</td>
		<td>10h30-11h15</td>
		<td>MDA</td>
	</tr>
	<tr>
		<td>6 ans</td>
		<td>2007</td>
		<td>Initiation 1</td>
		<td>Vendredi</td>
		<td>17h15-18h00</td>
		<td>Odyssée</td>
	</tr>
	<tr>
		<td>6-7 ans</td>
		<td>2006-2007</td>
		<td>Initiation Samedi</td>
		<td>Samedi</td>
		<td>11h15-12h00</td>
		<td>MDA</td>
	</tr>
	<tr>
		<td>7-8 ans</td>
		<td>2005-2006</td>
		<td>Initiation 2</td>
		<td>Vendredi</td>
		<td>18h00-18h45</td>
		<td>Odyssée</td>
	</tr>
	<tr>
		<td>9-10 ans</td>
		<td>2003-2004</td>
		<td>Pré-Jazz</td>
		<td>Lundi</td>
		<td>17h00-18h00</td>
		<td>Odyssée</td>
	</tr>
	<tr>
		<td>11-12 ans</td>
		<td>2001-2002</td>
		<td>Pré-Ados</td>
		<td>Lundi</td>
		<td>18h00-19h00</td>
		<td>Odyssée</td>
	</tr>
	<tr>
		<td>13-16 ans</td>
		<td>1997-2000</td>
		<td>Ados</td>
		<td>Lundi</td>
		<td>19h00-20h00</td>
		<td>Odyssée</td>
	</tr>
	<tr>
		<td>Adultes débutants</td>
                <td></td>
		<td>Adultes débutants</td>
		<td>Vendredi</td>
		<td>19h15-20h15</td>
		<td>MDA</td>
	</tr>
	<tr>
		<td>Adultes intermédiaires</td>
                <td></td>
		<td>Adultes intermédiaires</td>
		<td>Lundi</td>
		<td>20h00-21h15</td>
		<td>Odyssée</td>
	</tr>
	<tr>
		<td>Adultes avancés</td>
                <td></td>
		<td>Adultes avancés</td>
		<td>Mardi</td>
		<td>21h00-22h15</td>
		<td>Odyssée</td>
	</tr>
</table>
</div>