<div id="tarifcontenu">
Le tarif à l'année comprend l'adhésion plus la cotisation :
<ul>
<li>Adhésion à l'association : 30€ par an et par personne.</li>
<li>La cotisation dépend de la durée du cours : 45 min, 1h ou 1h15.</li>
</ul>
<p>
Les tarifs des différents groupes sont résumés dans le tableau ci-dessous.
</p>
<table>
	<caption>Tarifs des différents groupes</caption>
	<tr>
		<th>Âge</th>
		<th>Nom du Groupe</th>
		<th>Durée</th>
		<th>Cotisation</th>
		<th>Total à l'année <br />dont l'adhésion de 30€</th>
	</tr>
	<tr>
		<td>4-5 ans</td>
		<td>Éveil</td>
		<td>45 min</td>
		<td>205€</td>
		<td>235€</td>
	</tr>
	<tr>
		<td>4-5 ans</td>
		<td>Éveil Samedi</td>
		<td>45 min</td>
		<td>205€</td>
		<td>235€</td>
	</tr>
	<tr>
		<td>6 ans</td>
		<td>Initiation 1</td>
		<td>45 min</td>
		<td>205€</td>
		<td>235€</td>
	</tr>
	<tr>
		<td>6-7 ans</td>
		<td>Initiation Samedi</td>
		<td>45 min</td>
		<td>205€</td>
		<td>235€</td>
	</tr>
	<tr>
		<td>7-8 ans</td>
		<td>Initiation 2</td>
		<td>45 min</td>
		<td>205€</td>
		<td>235€</td>
	</tr>
	<tr>
		<td>9-10 ans</td>
		<td>Pré-Jazz</td>
		<td>1 heure</td>
		<td>220€</td>
		<td>250€</td>
	</tr>
	<tr>
		<td>11-12 ans</td>
		<td>Pré-Ados</td>
		<td>1 heure</td>
		<td>220€</td>
		<td>250€</td>
	</tr>
	<tr>
		<td>13-16 ans</td>
		<td>Ados</td>
		<td>1 heure</td>
		<td>220€</td>
		<td>250€</td>
	</tr>
	<tr>
		<td>Adultes débutants</td>
		<td>Adultes débutants</td>
		<td>1 heure</td>
		<td>220€</td>
		<td>250€</td>
	</tr>
	<tr>
		<td>Adultes intermédiaires</td>
		<td>Adultes intermédiaires</td>
		<td>1 heure 15</td>
		<td>260€</td>
		<td>290€</td>
	</tr>
	<tr>
		<td>Adultes intermédiaires</td>
		<td>Adultes avancés</td>
		<td>1 heure 15</td>
		<td>260€</td>
		<td>290€</td>
	</tr>
</table>

<p>Le 2e adhérent et les suivants d’une même famille (parents et enfants directs uniquement) 
bénéficient d’une remise sur la cotisation annuelle ; les adhérents qui prennent 
deux cours par semaine également.</p>
<p>L’adhésion est à régler à l’inscription en totalité. La cotisation peut être réglée en une fois en début d’année, ou en trois fois. 
Dans ce cas les trois règlements (en chèques) doivent être remis à l’inscription ; ils seront encaissés en septembre, janvier et avril.</p>

<p>L’inscription est prise pour l’année entière, aucun remboursement ne pourra être effectué pour convenance personnelle.</p>
</div>