<div class="alert-primary alert">
Le tarif à l'année comprend l'adhésion plus la cotisation :
    <ul class="mb-0">
        <li>Adhésion à l'association : 30€ par an et par personne.</li>
        <li>La cotisation dépend de la durée du cours : 45 min, 1h ou 1h15 et de l'âge.</li>
    </ul>
</div>
<p>
Les tarifs des différents groupes sont résumés dans le tableau ci-dessous.
</p>
<table class="table table-striped">
	<tr>
		<th>Âge</th>
		<th>Nom du Groupe</th>
		<th>Durée</th>
		<th>Tarif</th>
	</tr>
	<?php foreach ($this->groupes as $group) { ?>
	<tr>
		<td><?php echo $group["age"]; ?></td>
		<td><?php echo $group["nom"]; ?></td>
		<td><?php echo $group["duree"]; ?></td>
		<td><?php echo $group["tarif"]; ?></td>
	</tr>
	<?php } ?>
</table>

<h3>Tarifs spéciaux</h3>

<p class="alert-info alert"> Le 2e adhérent et les suivants d'une même famille (parents et enfants uniquement)
bénéficient d'une remise sur la cotisation annuelle. </p>

<h3>Forfaits</h3>
<p>
Forfaits disponibles :
</p>
<ul>
<li>Forfait concours : 250 €. Il est destiné aux élèves à partir de 8 ans, et comporte 15 séances dans l'année ainsi
qu'un accompagnement aux concours.</li>
<li>Barre à terre, pilates et étirements : 1 vendredi sur deux. Prévoir une adhésion de 30 € pour les non-adhérents.</li>
<li>Deux cours pour une même personne : -40% sur le deuxième cours.</li>
</ul>

<p class="alert-primary alert">L’adhésion est à régler à l’inscription en totalité. La cotisation peut être réglée en une fois en début d’année, ou en trois fois. 
Dans ce cas les trois règlements (en chèques NON datés) doivent être remis à l’inscription ; ils seront encaissés en septembre, janvier et avril.</p>
