<div id="tarifcontenu">
Le tarif à l'année comprend l'adhésion plus la cotisation :
<ul>
<li>Adhésion à l'association : 30€ par an et par personne.</li>
<li>La cotisation dépend de la durée du cours : 45 min, 1h ou 1h15.</li>
</ul>
<p>
Les tarifs des différents groupes sont résumés dans le tableau ci-dessous.
</p>
<table>
	<caption>Tarifs des différents groupes</caption>
	<tr>
		<th>Âge</th>
		<th>Nom du Groupe</th>
		<th>Durée</th>
		<th>Tarif</th>
	</tr>
	<tr>
		<td>4 - 5 ans</td>
		<td>Éveil 1</td>
		<td>45 min</td>
		<td>245€</td>
	</tr>
	<tr>
		<td>5 - 6 ans</td>
		<td>Éveil 2</td>
		<td>45 min</td>
		<td>245€</td>
	</tr>
	<tr>
		<td>6 - 7 ans</td>
		<td>Initiation 1</td>
		<td>45 min</td>
		<td>245€</td>
	</tr>
	<tr>
		<td>7 - 8 ans</td>
		<td>Initiation 2</td>
		<td>45 min</td>
		<td>245€</td>
	</tr>
	<tr>
		<td>8 ans et plus</td>
		<td>Groupe chorégraphique</td>
		<td>1 heure 15</td>
		<td>110€ ou forfait</td>
	</tr>
	<tr>
		<td>8 ans et plus</td>
		<td>Approfondissement technique</td>
		<td>1 heure 30</td>
		<td>300€ ou forfait</td>
	</tr>
	<tr>
		<td>8 ans</td>
		<td>Pré-JAZZ 1</td>
		<td>1 heure</td>
		<td>260€</td>
	</tr>
	<tr>
		<td>9 ans</td>
		<td>Pré-JAZZ 2</td>
		<td>1 heure 15</td>
		<td>260€</td>
	</tr>
	<tr>
		<td>10 - 11 ans</td>
		<td>Pré-Ados 1</td>
		<td>1 heure 15</td>
		<td>260€</td>
	</tr>
	<tr>
		<td>12 - 14 ans</td>
		<td>Pré-Ados 2</td>
		<td>1 heure 15</td>
		<td>260€</td>
	</tr>
	<tr>
		<td>14 - 18 ans</td>
		<td>Ados</td>
		<td>1 heure</td>
		<td>260€</td>
	</tr>
	<tr>
		<td>Adultes</td>
		<td>Adultes 1</td>
		<td>1 heure</td>
		<td>260€</td>
	</tr>
	<tr>
		<td>Adultes</td>
		<td>Adultes 2</td>
		<td>1 heure 15</td>
		<td>300€</td>
	</tr>
	<tr>
		<td>Adultes</td>
		<td>Adultes 3</td>
		<td>1 heure 15</td>
		<td>300€</td>
	</tr>
</table>

<p>Le 2e adhérent et les suivants d’une même famille (parents et enfants directs uniquement) 
bénéficient d’une remise sur la cotisation annuelle ; les adhérents qui prennent 
deux cours par semaine également.</p>

<p>Le groupe chorégraphique disposera de 15 séances dans l'année ainsi que d'un accompagnement aux spectacles.
Les différentes possibilités pour le groupe chorégraphique et technique sont les suivants:
</p>
<ul>
<li>Forfait : 1 cours 1h + groupe chorégraphique pour 370€</li>
<li>Forfait : 1 cours 1h + approfondissement technique pour 410€</li>
<li>Forfait : 1 cours 1h + approfondissement technique + groupe chorégraphique pour 450€</li>
</ul>

<p>L’adhésion est à régler à l’inscription en totalité. La cotisation peut être réglée en une fois en début d’année, ou en trois fois. 
Dans ce cas les trois règlements (en chèques) doivent être remis à l’inscription ; ils seront encaissés en septembre, janvier et avril.</p>

<p>L’inscription est prise pour l’année entière, aucun remboursement ne pourra être effectué pour convenance personnelle.</p>
</div>