<div class="container">
<h4 class="mt-2">Agenda à venir</h4>
<div class="row justify-content-center">
<?php foreach ($this->actualites as $actualite) { ?>
	<div id="<?php echo $actualite['id']; ?>" class="card my-2" style="width: 330px; margin:auto">
      <h5>
        <div class="card-header">
      		<?php echo $actualite['titre']; ?>
        </div>
      </h5>
      <div class="card-body">
        <h6 class="card-subtitle mb-2 text-muted"><?php echo $actualite['longdate']; ?></h6>
        <?php echo $actualite['description']; ?>
      </div>
    </div>
<?php } ?>
</div>
</div>