<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml"> 
    <head>  
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> 
        <meta name="keywords" content="danse eybens, danse, eybens, laura mosio, 
              jazz eybens, modern jazz eybens, association impulstion, impulsion danse, impulsion eybens,
              cours de danse eybens, cours de danse, cours de danse laura mosio, cours de danse impulsion,
              danse enfant eybens, danse adulte eybens, cours de danse enfant eybens" />
        <title>Impulsion</title>
        <script src="<?php echo ROOT_TO_PUBLIC; ?>/js/lib/jquery-3.2.1.min.js" type="text/javascript"></script>
        <script src="<?php echo ROOT_TO_PUBLIC; ?>/js/lib/bootstrap.bundle.min-4.1.3.js" type="text/javascript"></script>
        <script src="<?php echo ROOT_TO_PUBLIC; ?>/js/loading.js" type="text/javascript"></script>
        <link rel="stylesheet" type="text/css" href="<?php echo ROOT_TO_PUBLIC; ?>/css/lib/bootstrap.min-4.1.3.css" />
        <?php
        // get the current controller
        $controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
        $action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
        ?>
        <link rel="stylesheet" type="text/css" href="<?php echo ROOT_TO_PUBLIC; ?>/css/global.css" />
        <?php if ($controller == "liens") { ?>
            <script type="text/javascript" src="<?php echo ROOT_TO_PUBLIC; ?>/js/contact.js" ></script>	
        <?php } ?>
        <?php if ($controller == "galerie") { ?>
            <script type="text/javascript" src="<?php echo ROOT_TO_PUBLIC; ?>/js/rand_photo.js" ></script>
            <link rel="stylesheet" type="text/css" href="<?php echo ROOT_TO_PUBLIC; ?>/css/lib/thickbox.css" />
            <script type="text/javascript" src="<?php echo ROOT_TO_PUBLIC; ?>/js/lib/thickbox.js" ></script>
        <?php } ?>  
    </head> 
    <body>
    	<div id="main_div" class="container bg-white pb-3">
    		<div>
    			<img class="img-fluid" src="<?php echo ROOT_TO_PUBLIC; ?>/image/fond-menu.png" />
    		</div>
    		<div>
                <?php $auth = Zend_Auth::getInstance(); 
                if ($auth->hasIdentity()) {
                echo '<span id="loginfields">Bonjour ' . $auth->getIdentity()->username
                . ' - <a href="'
                . $this->url(array('controller' => "login", "action" => "logout"))
                . '">se déconnecter</a></span>';
                }
                ?>
    		</div>
            <ul class="nav nav-pills mt-3" style="background-color: gray">
              <li class="nav-item">
              	<?php if ($controller == "index") { ?>
                	<a class="nav-link text-white active" href="<?php echo $this->url(array('controller' => "index", "action" => "index"), "", true); ?>">Accueil</a>
                <?php } else { ?> 
                	<a class="nav-link text-white" href="<?php echo $this->url(array('controller' => "index", "action" => "index"), "", true); ?>">Accueil</a>
                <?php } ?>
              </li>
              <li class="nav-item dropdown">
                <?php if ($controller == "cours") { ?>
                    <a class="nav-link text-white dropdown-toggle active" data-toggle="dropdown" href="<?php echo $this->url(array('controller' => "cours", "action" => "index"), "", true); ?>" role="button" aria-haspopup="true" aria-expanded="false">Les cours</a>
                <?php } else { ?>
                    <a class="nav-link text-white dropdown-toggle" data-toggle="dropdown" href="<?php echo $this->url(array('controller' => "cours", "action" => "index"), "", true); ?>" role="button" aria-haspopup="true" aria-expanded="false">Les cours</a>
                <?php } ?>
                    <div class="dropdown-menu">
                      <a class="dropdown-item" href="<?php echo $this->url(array('controller' => "cours", "action" => "plan"), "", true); ?>">Plan</a>
                      <a class="dropdown-item" href="<?php echo $this->url(array('controller' => "cours", "action" => "planning"), "", true); ?>">Planning</a>
                      <a class="dropdown-item" href="<?php echo $this->url(array('controller' => "cours", "action" => "tarif"), "", true); ?>">Tarifs</a>
                      <a class="dropdown-item" href="<?php echo $this->url(array('controller' => "cours", "action" => "dossier"), "", true); ?>">Inscription</a>
                    </div>
              </li>
              <li class="nav-item">
                <?php if ($controller == "liens") { ?>
                	<a class="nav-link text-white active" href="<?php echo $this->url(array('controller' => "liens", "action" => "index"), "", true); ?>">Contacts</a>
                <?php } else { ?>
                	<a class="nav-link text-white" href="<?php echo $this->url(array('controller' => "liens", "action" => "index"), "", true); ?>">Contacts</a>
                <?php } ?>
              </li>
              <li class="nav-item">
                <?php if ($controller == "galerie") { ?>
	                <a class="nav-link text-white active" href="<?php echo $this->url(array('controller' => "galerie", "action" => "index"), "", true); ?>">Galerie Photos</a>
                <?php } else { ?>
	                <a class="nav-link text-white" href="<?php echo $this->url(array('controller' => "galerie", "action" => "index"), "", true); ?>">Galerie Photos</a>
                <?php } ?>
              </li>
              <li class="nav-item">
                <a class="nav-link text-white" href="/mag">Boutique photos</a>
              </li>
            </ul>
            <div> 
                <?php echo $this->layout()->content; ?>
            </div>  	
            <div id="loading"></div>
    	</div>
    </body>
</html>
